apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAzureContainerAllowedImages
metadata:
  name: container-allowed-images
spec:
  excludedNamespaces: {{ .Values.excludedNamespaces }}
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    imageRegex: {{ .Values.allowedContainerImagesRegex }}