apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sContainerAllowedPorts
metadata:
  name: container-allowed-ports
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaceSelector:
      matchExpressions:
      - key: control-plane
        operator: DoesNotExist
  parameters:
    allowedPorts: {{ .Values.allowedContainerPorts }}