#
# This YAML file can be used to test policy "Enforce labels on pods in Kubernetes cluster".
#
# Assumption for testing purposes: A pod is compliant if it has labels 'owner' and 'team'
#
# This YAML file creates a compliant pod in prod namespace.
apiVersion: v1
kind: Pod
metadata:
  name: nginx-app-compl-prod
  namespace: prod-ns
  labels:
    run: nginx-app-compl-prod
    owner: policy
    team: azuredg
spec:
  containers:
  - image: nginx
    name: nginx-app-compl-prod
    ports:
    - containerPort: 8282
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}