#
# This YAML file can be used to test policy "Enforce labels on pods in Kubernetes cluster".
#
# Assumption for testing purposes: A pod is compliant if it has labels 'owner' and 'team'
#
# This YAML file creates a non-compliant deployment in test namespace
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy-non-compl-test
  namespace: test-ns
  labels:
    app: nginx-deploy-non-compl-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-deploy-non-compl-test
  template:
    metadata:
      labels:
        app: nginx-deploy-non-compl-test
    spec:
      containers:
      - name: nginx-deploy-non-compl-test
        image: nginx
        ports:
        - containerPort: 9090