#
# This YAML file can be used to test policy "Enforce labels on pods in Kubernetes cluster".
#
# Assumption for testing purposes: A pod is compliant if it has labels 'owner' and 'team'
#
# This YAML file creates a non-compliant job in a namespace that has control-plane label.
apiVersion: batch/v1
kind: Job
metadata:
  name: pi-job-non-compl-control-plane
  namespace: gatekeeper-system
spec:
  template:
    metadata:
      labels:
        app: pi-job-non-compl-control-plane
    spec:
      containers:
      - name: pi-job-non-compl-control-plane
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4