#
# This YAML file can be used to test policy "Enforce labels on pods in Kubernetes cluster".
#
# Assumption for testing purposes: A pod is compliant if it has labels 'owner' and 'team'
#
# This YAML file creates a non-compliant job in test namespace
apiVersion: batch/v1
kind: Job
metadata:
  name: pi-job-non-compl-test
  namespace: test-ns
spec:
  template:
    metadata:
      labels:
        app: pi-job-non-compl-test
    spec:
      containers:
      - name: pi-job-non-compl-test
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4