apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAzureContainerLimits
metadata:
  name: container-limits
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaceSelector:
      matchExpressions:
      - key: control-plane
        operator: DoesNotExist
  parameters:
    cpuLimit : "{{ .Values.cpuLimit }}"
    memoryLimit: "{{ .Values.memoryLimit }}"
