apiVersion: v1
kind: Pod
metadata:
  name: container-resourcelimits-bad2
spec:
  containers:
  - name: memory-demo-ctr-bad2
    image: polinux/stress
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]
  - name: nginx-bad2
    image: nginx
    resources:
      limits:
        memory: 100Mi
        cpu: 100Mi