apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAzureContainerLimits
metadata:
  name: container-limits
spec:
  excludedNamespaces: {{ .Values.excludedNamespaces }}
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    cpuLimit : "{{ .Values.cpuLimit }}"
    memoryLimit: "{{ .Values.memoryLimit }}"