# Default values for azure policy add-on on AKS Engine, a self managed Kubernetes cluster on Azure.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Microsoft Azure Policy Add-on on AKS Engine
azurepolicy:
  image:
    name: "mcr.microsoft.com/azure-policy/policy-kubernetes-addon-prod"
    tag: "prod_20200227.1"
## Replace <your_resource_id> with the resource group ID the AKS Engine cluster is in. For example: /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/testRG
  env:
    resourceid: <your_resource_id>

## OPA Gatekeeper for Kubernetes clusters
gatekeeper:
  image:
    name: "mcr.microsoft.com/oss/open-policy-agent/gatekeeper"
    tag: "v3.1.0-beta.7"
  args:
    auditIntervalSeconds: 60
    constraintViolationsLimit: 20
  resources:
    cpuLimit: 1000m
    memoryLimit: 512Mi
    cpuRequests: 100m
    memoryRequests: 256Mi
