apiVersion: v1
entries:
  azure-policy-addon-arc-connected-clusters:
  - apiVersion: v1
    appVersion: "1"
    created: "2020-02-24T13:30:48.9201514-08:00"
    description: Helm chart for deploying Azure Policy Add-on on Azure Arc for Kubernetes
      clusters.
    digest: 5ff5b0cd823fca5bce853b0a3a813a8f70d3bc874451729bf60f7e32b5dc9e8b
    home: https://docs.microsoft.com/en-us/azure/governance/policy/concepts/rego-for-aks?toc=/azure/aks/toc.json
    keywords:
    - azure
    - azure policy
    - azure-policy
    - governance
    - compliance
    - gatekeeper
    - opa
    - kubernetes policy
    - kubernetes-policy
    - arc connected clusters
    - arc-connected-clusters
    - azure arc for kubernetes clusters
    - azure-arc-for-kubernetes-clusters
    - kubernetes
    maintainers:
    - email: azuredg@microsoft.com
      name: azuredg
    name: azure-policy-addon-arc-connected-clusters
    sources:
    - https://github.com/Azure/azure-policy-kubernetes
    urls:
    - https://raw.githubusercontent.com/RamyasreeChakka/RegoPolicy/master/Kubernetes/helmcharts/azure-policy-addon-arc-connected-clusters-0.1.0.tgz
    version: 0.1.0
generated: "2020-02-24T13:30:48.9151199-08:00"
