apiVersion: v1
entries:
  azure-policy-addon-arc-connected-clusters:
  - apiVersion: v1
    appVersion: "1"
    created: "2020-02-04T07:23:11.8031902-08:00"
    description: Helm chart for deploying Azure Policy add-on in Azure Arc Kubernetes
      clusters.
    digest: 1653ed7a4432e90ee5616413a055d2862da6a29206ef8dfa9328e59a8a4e501f
    home: https://docs.microsoft.com/en-us/azure/governance/policy/concepts/rego-for-aks?toc=/azure/aks/toc.json
    keywords:
    - azure
    - azure policy
    - azure-policy
    - governance
    - compliance
    - gatekeeper
    - opa
    - kubernetes policy
    - kubernetes-policy
    - arc connected clusters
    - arc-connected-clusters
    - kubernetes
    maintainers:
    - email: azuredg@microsoft.com
      name: azuredg
    name: azure-policy-addon-arc-connected-clusters
    sources:
    - https://github.com/Azure/azure-policy-kubernetes
    urls:
    - https://raw.githubusercontent.com/RamyasreeChakka/RegoPolicy/master/Kubernetes/helmcharts/azure-policy-addon-arc-connected-clusters-0.1.0.tgz
    version: 0.1.0
generated: "2020-02-04T07:23:11.8031902-08:00"
