apiVersion: v1
appVersion: 1.0
description: Helm chart for deploying Azure Policy Add-on on Azure Arc for Kubernetes clusters.
name: azure-policy-addon-arc-connected-clusters
version: 0.1.0
keywords:
  - azure
  - azure policy
  - azure-policy
  - governance
  - compliance
  - gatekeeper
  - opa
  - kubernetes policy
  - kubernetes-policy
  - arc connected clusters
  - arc-connected-clusters
  - azure arc for kubernetes clusters
  - azure-arc-for-kubernetes-clusters
  - kubernetes
home: https://docs.microsoft.com/en-us/azure/governance/policy/concepts/rego-for-aks?toc=/azure/aks/toc.json
sources:
  - https://github.com/Azure/azure-policy-kubernetes
maintainers:
  - name: azuredg
    email: azuredg@microsoft.com
